### ISSUE TITLE
cannot download HRSCD dataset?

### ISSUE THREAD

**Issue by fuweifuvtoo** [wenhwu/awesome-remote-sensing-change-detection#10]
official information is：

The 2006 images are under a non-redistributable licence, but can be downloaded directly from IGN's website ( https://geoservices.ign.fr/documentation/diffusion/telechargement-donnees-libres.html#bd-ortho-50-cm or https://www.geoportail.gouv.fr/carte). The necessary files are:
    - BD ORTHO® 50 cm, D 14 - CALVADOS, 2005
    - BD ORTHO® 50 cm, D 35 - ILLE-ET-VILLAINE, 2006
For help with downloading the images please contact the authors.

but i can not download 2006 images from that urls, who can help me? I also cannot find authors emails;
who has already download that dataset?

**Comment by wenhwu** [comment]
I encountered the same problem. 

There is the author's email address on [README](https://ieee-dataport.org/open-access/hrscd-high-resolution-semantic-change-detection-dataset). Maybe you can contact [rcdaudt](https://github.com/rcdaudt) directly.

**Comment by fuweifuvtoo** [comment]
okk,and here is the rcdaudt's new email:


The following E-Mail    : rodrigo.daudt@onera.fr is no longer available or is outdated.

Information complémentaire / Extra information :

======
This email address will stop working soon. 
Please contact me at rodrigo.cayedaudt@geod.baug.ethz.ch or using the links found on my personal website: https://rcdaudt.github.io/
======

**Comment by XiaoJ058** [comment]
Do you have the HRSCD dataset? The land cover labels for 2006 that I downloaded from the official website are the same as those for 2012.

**Comment by Harsh-1807** [comment]
any updates on how to download the 2006 data?
