### ISSUE TITLE
Annotation tool for change detection recommendation

### ISSUE THREAD

**Issue by wahyuwiratama** [wenhwu/awesome-remote-sensing-change-detection#11]
Hello, thank you for a very interesting information.
Do you have any recommendation annotation tools for change detection such as labelme for image segmentation?
I hope I can find it for a better dataset annotation. Thank you

**Comment by wenhwu** [comment]
@wahyuwiratama , Sorry for my late reply, in my personal experience, it is enough to make training samples with [ENVI](https://www.l3harrisgeospatial.com/Software-Technology/ENVI).
