### ISSUE TITLE
BCDD dataset

### ISSUE THREAD

**Issue by Luiweony** [wenhwu/awesome-remote-sensing-change-detection#12]
Could you please tell me where I can find the BCDD data set? Thank you！

**Comment by YangTze7** [comment]
BCCD dataset is part of WHU Building change detection Dataset

**Comment by YangTze7** [comment]
> Could you please tell me where I can find the BCDD data set? Thank you！

I figure that  BCCD dataset is  **WHU Building change detection Dataset** described in readme

**Comment by wenhwu** [comment]
@Luiweony , Sorry for my late reply. Just as @YangTze7  said, BCCD Dataset is WHU Building Change Detection Dataset.
