### ISSUE TITLE
Please add new SAR CD dataset

### ISSUE THREAD

**Issue by sudipansaha** [wenhwu/awesome-remote-sensing-change-detection#15]
We have recently extended the Onera S2 CD dataset with Sentinel-1 SAR images. The extension can be used for either SAR-SAR CD or Optical-SAR multi-modal CD.

Here is the link to the extended dataset: https://github.com/PatrickTUM/multimodalCD_ISPRS21

Here is the paper that describes the extension: https://www.int-arch-photogramm-remote-sens-spatial-inf-sci.net/XLIII-B3-2021/243/2021/isprs-archives-XLIII-B3-2021-243-2021.pdf

Requesting admin to kindly add this dataset.

**Comment by wenhwu** [comment]
Thank you for sharing. 

Dataset has been added to the page.
