### ISSUE TITLE
Do you have PCC code？

### ISSUE THREAD

**Issue by ghost** [wenhwu/awesome-remote-sensing-change-detection#2]
Thanks，i need it

**Comment by wenhwu** [comment]
Could you give the details of the PCC ？

**Comment by wenhwu** [comment]
If PCC is post classification comparison, maybe you can look at this :   [GWA_scripts/scripts/GWA_TBX/postclassificationComparison.py](https://github.com/GlobWetlandAfrica/GWA_scripts/blob/526c9cd0fdccf1b2ab66105823133a151583f1cb/scripts/GWA_TBX/postclassificationComparison.py)

**Comment by ghost** [comment]
感谢您的答复！
我看到多数“异质遥感图像变化检测”的论文中使用PCC（“Inland wetland change detection using aircraft
MSS data”）作为他们实验中的对比方法，例如“Coupled Dictionary Learning for Change Detection
From Multisource Data”这篇文章中的对比方法，您知道PCC的相关代码或者论文吗？

wenhwu <notifications@github.com> 于2020年1月5日周日 下午5:23写道：

**Comment by ghost** [comment]
非常感谢您的热心答复，我找了好久都没找到，我需要的就是这个！感谢您

wenhwu <notifications@github.com> 于2020年1月5日周日 下午5:31写道：

**Comment by wenhwu** [comment]
我看了一下Coupled Dictionary Learning for Change Detection From Multisource Data这篇文章，文章里这么形容PCC: PCC is greatly dependent on the quality of the classified maps, and the individual errors would compound in the final change map, which accounts for the noisy detection result。也就是说PCC就是post classification comparison(分类后变化检测）。

PCC只是一种做变化检测的思路，任何分类的方法都可以套进去。

上面的代码只是我临时搜的，可能也没啥用，:)

**Comment by ghost** [comment]
总之非常感谢了，刚开始做CD的一个实验，做完之后找对比方法找了好久，都很难找到源码，我在你的git里再找找有没有容易跑通的，如果真的要复现对比实验的话，对我来说难度有点大，感谢你热心的答复。

wenhwu <notifications@github.com> 于2020年1月5日周日 下午5:42写道：
