### ISSUE TITLE
ChangeNet dataset

### ISSUE THREAD

**Issue by likyoo** [wenhwu/awesome-remote-sensing-change-detection#25]
I found a new dataset - maybe suitable for this repo.

paper: https://arxiv.org/abs/2312.17428
data: https://github.com/jankyee/ChangNet

https://pan.baidu.com/s/12X2sjiWPaOrtBceNBoVdrQ (Password: dikc)

**Comment by wenhwu** [comment]
Thank you very much for sharing the information, which I have now included in the repo. 

ChangeNet is currently the largest multi-category dataset available. After reviewing the paper and downloading the entire ChangeNet dataset (approximately 80.1 GB), I feel that the definition of the dataset isn't very clear, which might necessitate data cleansing for effective usage.
