### ISSUE TITLE
Hi-UCD

### ISSUE THREAD

**Issue by nzbanana** [wenhwu/awesome-remote-sensing-change-detection#26]
Hello, I found that the link of the data set Hi-UCD cannot be opened any more. Do you have the latest download address?

**Comment by wenhwu** [comment]
@nzbanana ,Thank you for the reminder. 

I have updated the link to the Hi-UCD dataset. Please find the Hi-UCD dataset through this [link](https://github.com/Daisy-7/Hi-UCD-S).
