### ISSUE TITLE
How to download the SMARS dataset

### ISSUE THREAD

**Issue by Billy-ZTB** [wenhwu/awesome-remote-sensing-change-detection#27]
The download link in the website which was posted in the paper is invalid now.

**Comment by wenhwu** [comment]
Thank you for the reminder, perhaps you can try this [link](https://www.dlr.de/en/eoc/about-us/remote-sensing-technology-institute/photogrammetry-and-image-analysis/public-datasets/smars).

**Comment by Billy-ZTB** [comment]
Thanks! I've found that. But I wonder if this released dataset is the full dataset, because I noticed that the size of this released dataset is much smaller than that they claimed to be:
![image](https://github.com/wenhwu/awesome-remote-sensing-change-detection/assets/52749583/1308baea-3047-4e80-b476-63e18ac8d667)
![image](https://github.com/wenhwu/awesome-remote-sensing-change-detection/assets/52749583/8fdf2a6b-13bc-4c98-a52a-171e596ed32d)

**Comment by wenhwu** [comment]
Maybe you could try decompressing the dataset to see if it reaches 9.0 GB. If I remember correctly, the classification map files can be compressed to a very small size.

**Comment by Billy-ZTB** [comment]
Thank you! I will download and try.



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/11/2024 23:31 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [wenhwu/awesome-remote-sensing-change-detection] How to download the SMARS dataset (Issue #27) |

Maybe you could try decompressing the dataset to see if it reaches 9.0 GB. If I remember correctly, the classification map files can be compressed to a very small size.
