### ISSUE TITLE
训练数据集

### ISSUE THREAD

**Issue by wangjnchuan** [wenhwu/awesome-remote-sensing-change-detection#4]
你好，http://captain.whu.edu.cn/WUDA-RSImg/scid.html，这里武汉大学的变化检测数据集请问你有没有获取到呀

**Comment by wenhwu** [comment]
你好，这个数据集还没有公布，只是留了个网页来占坑

**Comment by wangjnchuan** [comment]
好的，感谢，你知道这种数据集怎么做吗

**Comment by wenhwu** [comment]
请问你是要做哪方面的变化检测数据集，是只是变与不变，还是要做知道变化类型的变化检测数据集？

**Comment by wangjnchuan** [comment]
比如新增建筑物识别

**Comment by wenhwu** [comment]
您给的信息太少了，不同的数据集可能勾绘方式也不一样

一种通用的方法是将前后时相的影像加载进ENVI，然后不停地开和关某一时相的影像来判断新增情况，用勾shp的方式勾绘ground truth

**Comment by wangjnchuan** [comment]
我具体描述一下，我们这边是山东省国土测绘院，有个需求是根据我们切的影像瓦片，对比2018年的（影像和建筑物图斑shp），对2019年进行变化更新，所以需要找到每个瓦片内增加的建筑物，辅助我们数据生产人员发现这些增加的建筑物进行标绘，效果好的话，会扩展到其他地物，请问您有相关的技术吗

**Comment by wenhwu** [comment]
谢谢您提供的详细信息。我做过类似的实践，高分二号和航空影像都实验过。

深度学习的方法确实是可以作为辅助预判断的方法，但是需要大量的训练样本，理论上是越多越好，不过在我的实验里大概1对高分二号影像（即2幅影像，大概10000×6000大小）作为训练样本就可以实现一个还行的结果；另外，不同的数据集对于问题的定义也不一样，需要结合贵单位的需求来决定怎么勾绘数据集。

具体的方法您可以参考[广东政务数据创新大赛—智能算法赛](https://tianchi.aliyun.com/competition/entrance/231615/forum)，这是比赛的数据集的链接：https://pan.baidu.com/s/1tjw_akfpDjxLo4s4RKwCDw ，提取码：8r58

**Comment by wangjnchuan** [comment]
好的，十分感谢，我学习一下
